package it.grational

import groovy.util.logging.Slf4j

/**
 * This Groovy source file was auto generated by 'gigawatt'
 * @author d7392
 * @date 27-03-2021 09.42
 */
@Slf4j
class Library {
	/**
	 * This method returns always true.
	 */
	Boolean someLibraryMethod() {
		true
	}
}
