package it.grational

import spock.lang.Specification

/**
 * This Spock specification was auto generated by 'gigawatt'
 * @author d7392
 * @date 27-03-2021 09.42
 */
class LibraryUSpec extends Specification {
	def "someLibraryMethod returns true"() {
		setup:
			Library lib = new Library()
		when:
			Boolean result = lib.someLibraryMethod()
		then:
			result == true
	}
}
